#!/usr/bin/env raku
# Regenerate t/vectors/digest.vec from an INDEPENDENT oracle.
#
# The point of the file is to be an oracle this project did not compute, so it
# is built with the system `openssl` and never with our own code. Run it when a
# vector is added; the answers must not move otherwise.
#
#   raku tools/gen-vectors.raku > t/vectors/digest.vec

my @ALGOS = <md5 sha1 sha224 sha256 sha384 sha512>;

# An input is written <hex> or <hex>*<count>, so a million-byte message costs
# one line. `-` is the empty input.
sub spec(Str $s, Int $rep = 1) {
    return '-' if !$s && $rep == 1;
    my $hex = $s.encode('utf-8').list».fmt('%02x').join;
    $rep == 1 ?? $hex !! "$hex*$rep"
}
sub hexspec(Str $hex, Int $rep = 1) { $rep == 1 ?? $hex !! "$hex*$rep" }
sub unspec(Str $spec) {
    return Buf.new if $spec eq '-';
    my ($h, $n) = $spec.split('*');
    my $once = Buf.new($h.comb(2).map({ :16($_) }));
    # latin-1 is a byte-for-byte codec both ways, so `x` on the decoded text is
    # a C-level string repeat — a million-byte input costs no Raku list at all.
    $n ?? ($once.decode('latin-1') x +$n).encode('latin-1') !! $once
}

sub openssl-dgst(Str $algo, Blob $in) {
    my $p = run('openssl', 'dgst', "-$algo", :in, :out);
    $p.in.write($in); $p.in.close;
    $p.out.slurp(:close).trim.split(/\s+/).tail
}
sub openssl-hmac(Str $algo, Blob $key, Blob $msg) {
    my $kh = $key.list».fmt('%02x').join;
    my $p = run('openssl', 'dgst', "-$algo", '-mac', 'HMAC', '-macopt', "hexkey:$kh", :in, :out);
    $p.in.write($msg); $p.in.close;
    $p.out.slurp(:close).trim.split(/\s+/).tail
}

say q:to/HEAD/.chomp;
# digest.vec — conformance vectors for the `digest` family.
#
# ONE FILE, EVERY IMPLEMENTATION. Digest::Native's C, its ecosystem fallback,
# and (when DATA-PLAN P3 lands) the engine's own src/Digest.cpp are separate
# implementations on purpose — see NATIVE-MODULES-PLAN, "The architecture:
# independent C". This file is the thing that keeps them honest, so it is read
# by all of them and weakened by none of them.
#
# Generated by tools/gen-vectors.raku from the system openssl, never from our
# own code. Every published constant it contains was also checked by eye
# against RFC 1321, FIPS 180-4, RFC 2202 and RFC 4231.
#
#   H <algo> <input> <expected-hex>
#   M <algo> <blocksize|-> <key> <message> <expected-hex>
#
# <input>, <key> and <message> are hex, optionally <hex>*<count> for a repeat,
# and `-` for empty. A blocksize of `-` means the algorithm's own (RFC 2104),
# which is what this family uses when the caller does not say.
HEAD

# ---- hashes: the published suites -----------------------------------------
my @inputs =
    spec(''),
    spec('a'),
    spec('abc'),
    spec('message digest'),
    spec('abcdefghijklmnopqrstuvwxyz'),
    spec('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'),
    spec('1234567890', 8),
    spec('abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq'),          # FIPS 448-bit
    spec('abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmno'
       ~ 'ijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu'),                   # FIPS 896-bit
    spec('a', 1000000),                                                        # the long one
    hexspec('00'),                                                             # a NUL byte
    hexspec('00ff8041'),                                                       # bytes no text would carry
    hexspec('c3a9'),                                                           # é as UTF-8
    hexspec('61', 63), hexspec('61', 64), hexspec('61', 65),                    # block edges, 64
    hexspec('61', 127), hexspec('61', 128), hexspec('61', 129);                 # block edges, 128

say '';
for @ALGOS -> $a {
    for @inputs -> $in { say "H $a $in { openssl-dgst($a, unspec($in)) }" }
}

# ---- HMAC: RFC 2202 (md5, sha1) and RFC 4231 (sha2) ------------------------
my @cases =
    (hexspec('0b', 20), spec('Hi There')),
    (spec('Jefe'),      spec('what do ya want for nothing?')),
    (hexspec('aa', 20), hexspec('dd', 50)),
    (hexspec('0102030405060708090a0b0c0d0e0f10111213141516171819'), hexspec('cd', 50)),
    (hexspec('0c', 20), spec('Test With Truncation')),
    (hexspec('aa', 131), spec('Test Using Larger Than Block-Size Key - Hash Key First')),
    (hexspec('aa', 131), spec('This is a test using a larger than block-size key and a '
                            ~ 'larger than block-size data. The key is hashed before being '
                            ~ 'used by the HMAC algorithm.'));

say '';
for @ALGOS -> $a {
    for @cases -> ($k, $m) { say "M $a - $k $m { openssl-hmac($a, unspec($k), unspec($m)) }" }
}

# An EXPLICIT block size is deliberately not in this file. openssl always uses
# the algorithm's own, so it cannot be the oracle for `hmac(…, &sha512, 64)` —
# and computing that value with our own code would make the vector circular.
# Digest::HMAC is the honest oracle there, since 64 is its default for every
# hash, and t/02-hmac.t asserts it against exactly that.
