#!/usr/bin/env python3
# Writes lib/Math/Wavelet/Table.rakumod: the filter bank of every discrete
# wavelet PyWavelets knows, as the shortest decimal that round-trips each
# double, so the Raku side parses back the identical bits.
#
#   python3 tools/gen-table.py > lib/Math/Wavelet/Table.rakumod
#
# Orthogonal wavelets store dec_lo only: the other three filters follow from it
# by reversal and alternating sign, which is exact, and this script asserts
# that they come out bit-identical to PyWavelets' own. Biorthogonal ones store
# all four, because their sign convention is not uniform across the family.

import pywt

FAMILIES = ['haar', 'db', 'sym', 'coif', 'bior', 'rbio', 'dmey']

def r(xs):
    return ' '.join(repr(float(x)) for x in xs)

def derived(dl):
    F = len(dl)
    rl = dl[::-1]
    rh = [(-1) ** k * dl[k] for k in range(F)]
    return rl, rh[::-1], rh

lines = []
for fam in FAMILIES:
    for name in pywt.wavelist(fam, kind='discrete'):
        w = pywt.Wavelet(name)
        dl, dh, rl, rh = (list(f) for f in w.filter_bank)
        head = '\t'.join([name, fam, w.family_name, w.symmetry,
                          str(w.vanishing_moments_psi or 0),
                          str(w.vanishing_moments_phi or 0)])
        if w.orthogonal:
            drl, ddh, drh = derived(dl)
            assert (drl, ddh, drh) == (rl, dh, rh), name
            assert all(str(a) == str(b) for a, b in zip(ddh + drh, dh + rh)), name
            lines.append(f'{head}\to\t{r(dl)}')
        else:
            lines.append(f'{head}\tb\t{r(dl)}\t{r(dh)}\t{r(rl)}\t{r(rh)}')

print(f'''# GENERATED by tools/gen-table.py from PyWavelets {pywt.__version__} — do not edit.
#
# One wavelet per line, tab-separated: name, short family, family, symmetry,
# vanishing moments of psi and phi, then 'o' and dec_lo for an orthogonal
# wavelet, or 'b' and dec_lo, dec_hi, rec_lo, rec_hi for a biorthogonal one.
# Kept as one string so that compiling this module costs nothing; a wavelet's
# line is parsed the first time it is asked for.

unit module Math::Wavelet::Table;

our constant TABLE = q:to/END/;''')
print('\n'.join(lines))
print('END')
