#!/usr/bin/env python3
# Writes t/vectors/*.vec: inputs and the outputs PyWavelets gives for them.
# Every expected value in t/ comes from here, never from this module's own
# code.
#
#   python3 tools/gen-vectors.py t/vectors
#
# One case per line, tab-separated. A numeric field is space-separated
# doubles to thirteen significant digits; '|' separates the arrays of a list,
# and ';' the rows of a matrix.

import sys, os
import numpy as np
import pywt

out_dir = sys.argv[1]
rng = np.random.default_rng(20261001)

# Thirteen significant digits: t/ checks agreement to a part in 10¹⁰, so the
# last four digits of a double would only make the files bigger.
def v(xs):
    return ' '.join(f'{float(x):.13g}' for x in np.ravel(xs))

def m(a):
    return ';'.join(v(row) for row in np.atleast_2d(a))

def signal(n):
    return np.round(rng.standard_normal(n) * 10, 3)

def write(name, lines, header):
    with open(os.path.join(out_dir, name), 'w') as f:
        f.write(f'# GENERATED by tools/gen-vectors.py from PyWavelets {pywt.__version__} — do not edit.\n')
        for h in header:
            f.write(f'# {h}\n')
        f.write('\n'.join(lines) + '\n')

MODES = ['zero', 'constant', 'symmetric', 'periodic', 'smooth',
         'periodization', 'reflect', 'antisymmetric', 'antireflect']

# A sample from every family, short and long, and the filter lengths at
# both extremes: a 76-tap db38 over a 5-sample signal is mostly extension.
WAVELETS = ['haar', 'db2', 'db5', 'db38', 'sym7', 'coif2', 'bior1.3',
            'bior2.2', 'bior3.9', 'bior6.8', 'rbio2.4', 'rbio3.1', 'dmey']

# ---- single level --------------------------------------------------------

lines = []
for w in WAVELETS:
    for mode in MODES:
        for n in (1, 2, 5, 13, 30):
            x = signal(n)
            try:
                a, d = pywt.dwt(x, w, mode=mode)
            except ValueError:
                continue
            lines.append('\t'.join(['dwt', w, mode, v(x), v(a), v(d)]))
            # The inverse is checked on coefficients that no signal produced,
            # so it is the transform itself under test, not a round trip.
            ra, rd = signal(len(a)), signal(len(d))
            try:
                y = pywt.idwt(ra, rd, w, mode=mode)
            except ValueError:
                continue
            lines.append('\t'.join(['idwt', w, mode, v(ra), v(rd), v(y)]))
    # either half absent
    ra = signal(40)
    lines.append('\t'.join(['idwt', w, 'symmetric', v(ra), '-',
                            v(pywt.idwt(ra, None, w, mode='symmetric'))]))
    lines.append('\t'.join(['idwt', w, 'periodization', '-', v(ra),
                            v(pywt.idwt(None, ra, w, mode='periodization'))]))
write('dwt.vec', lines, [
    'dwt  wavelet mode x cA cD',
    'idwt wavelet mode cA cD y   (- for an absent half)'])

# ---- lengths ------------------------------------------------------------

lines = []
for w in ['haar', 'db2', 'db10', 'sym8', 'coif3', 'bior2.2', 'dmey']:
    F = pywt.Wavelet(w).dec_len
    for n in (1, 2, 3, 7, 8, 64, 100, 1000, 1023, 1024):
        lines.append('\t'.join(['max-level', w, str(n),
                                str(pywt.dwt_max_level(n, F))]))
        for mode in ('symmetric', 'periodization'):
            lines.append('\t'.join(['coeff-len', w, mode, str(n),
                                    str(pywt.dwt_coeff_len(n, F, mode))]))
write('length.vec', lines, [
    'max-level wavelet n level',
    'coeff-len wavelet mode n length'])

# ---- multilevel ---------------------------------------------------------

lines = []
for w in ['haar', 'db3', 'sym4', 'coif2', 'bior2.4', 'rbio1.5']:
    for mode in MODES:
        for n, level in ((40, None), (37, 3), (10, 1)):
            x = signal(n)
            c = pywt.wavedec(x, w, mode=mode, level=level)
            y = pywt.waverec(c, w, mode=mode)
            lines.append('\t'.join(['wavedec', w, mode,
                                    '-' if level is None else str(level),
                                    v(x), '|'.join(v(k) for k in c), v(y)]))
write('wavedec.vec', lines, [
    'wavedec wavelet mode level x cA_n|cD_n|...|cD_1 waverec(coeffs)'])

# ---- stationary ---------------------------------------------------------

lines = []
for w in ['haar', 'db2', 'sym4', 'coif1', 'bior2.2', 'rbio3.3']:
    for n, level in ((8, 1), (16, 2), (24, None)):
        for start in (0, 1):
            for norm in (False, True):
                x = signal(n)
                try:
                    c = pywt.swt(x, w, level=level, start_level=start, norm=norm)
                except ValueError:
                    continue
                flat = [k for pair in c for k in pair]
                y = pywt.iswt(c, w, norm=norm) if start == 0 else None
                lines.append('\t'.join([
                    'swt', w, '-' if level is None else str(level), str(start),
                    'norm' if norm else '-', v(x), '|'.join(v(k) for k in flat),
                    '-' if y is None else v(y)]))
write('swt.vec', lines, [
    'swt wavelet level start-level norm x cA_n|cD_n|...|cA_1|cD_1 iswt(coeffs)'])

# ---- two-dimensional ----------------------------------------------------

lines = []
for w in ['haar', 'db2', 'bior2.2', 'sym3']:
    for mode in ('symmetric', 'periodization', 'smooth'):
        for shape in ((6, 9), (5, 4)):
            x = np.round(rng.standard_normal(shape) * 10, 3)
            a, (h, vv, d) = pywt.dwt2(x, w, mode=mode)
            ra, rh, rv, rd = (np.round(rng.standard_normal(a.shape), 3)
                              for _ in range(4))
            y = pywt.idwt2((ra, (rh, rv, rd)), w, mode=mode)
            lines.append('\t'.join(['dwt2', w, mode, m(x), m(a), m(h), m(vv), m(d)]))
            lines.append('\t'.join(['idwt2', w, mode, m(ra), m(rh), m(rv), m(rd), m(y)]))
        x = np.round(rng.standard_normal((14, 11)) * 10, 3)
        c = pywt.wavedec2(x, w, mode=mode, level=2)
        y = pywt.waverec2(c, w, mode=mode)
        flat = [c[0]] + [k for t in c[1:] for k in t]
        lines.append('\t'.join(['wavedec2', w, mode, '2', m(x),
                                '|'.join(m(k) for k in flat), m(y)]))
write('dwt2.vec', lines, [
    'dwt2     wavelet mode x cA cH cV cD',
    'idwt2    wavelet mode cA cH cV cD y',
    'wavedec2 wavelet mode level x cA_n|cH_n|cV_n|cD_n|...|cD_1 waverec2(coeffs)'])

# ---- thresholding -------------------------------------------------------

lines = []
x = np.array([-3.5, -2.0, -1.25, -0.5, 0.0, 0.5, 1.0, 1.25, 2.0, 3.5])
for mode in ('soft', 'hard', 'garrote', 'greater', 'less'):
    for value in (1.0, 1.25, 2.5):
        for sub in (0.0, -9.0):
            y = pywt.threshold(x, value, mode=mode, substitute=sub)
            lines.append('\t'.join(['threshold', mode, repr(value), repr(sub),
                                    v(x), v(y)]))
write('threshold.vec', lines, [
    'threshold mode value substitute x y'])

# ---- denoising ----------------------------------------------------------
# VisuShrink as this module defines it: the noise level from the median
# absolute finest detail, the universal threshold sigma·sqrt(2 ln N), applied
# to every detail level and never to the approximation.

lines = []
t = np.linspace(0, 1, 128)
clean = np.sin(2 * np.pi * 3 * t) + 0.5 * np.sign(np.sin(2 * np.pi * 7 * t))
for w, level, mode in (('db4', None, 'soft'), ('sym8', 3, 'hard'),
                       ('haar', 4, 'garrote')):
    x = clean + 0.2 * rng.standard_normal(len(t))
    c = pywt.wavedec(x, w, mode='symmetric', level=level)
    sigma = np.median(np.abs(c[-1])) / 0.6745
    thr = sigma * np.sqrt(2 * np.log(len(x)))
    c = [c[0]] + [pywt.threshold(k, thr, mode=mode) for k in c[1:]]
    y = pywt.waverec(c, w, mode='symmetric')[:len(x)]
    lines.append('\t'.join(['denoise', w, '-' if level is None else str(level),
                            mode, repr(float(sigma)), repr(float(thr)), v(x), v(y)]))
write('denoise.vec', lines, [
    'denoise wavelet level mode sigma threshold x y'])
