#!/usr/bin/env raku
# Regenerate t/vectors/zlib.vec from INDEPENDENT oracles.
#
# Compression is not a function — two correct deflaters produce different bytes
# for the same input — so what can be pinned is the other direction: a stream
# somebody else produced must decompress to exactly the bytes they compressed.
# These vectors are therefore built with real libz (through Compress::Zlib) and
# the system gzip, never with our own code, and they pin INFLATE, the checksums,
# and the streams that must be refused.
#
#   raku tools/gen-vectors.raku > t/vectors/zlib.vec
#
# Run under Rakudo: Compress::Zlib is the oracle here, and on Raku++ this
# distribution's own extension would be the thing under test.

use Compress::Zlib;

sub hex(Blob $b) { $b.list».fmt('%02x').join }
sub unhex(Str $h) { Buf.new($h.comb(2).map({ :16($_) })) }

my @inputs =
    ''                                                   => 'empty',
    'a'                                                  => 'one byte',
    'hello world'                                        => 'short',
    ('ab' x 5000)                                        => 'a long run of one pair',
    ('The quick brown fox jumps over the lazy dog. ' x 200) => 'repeated prose',
    (^4096).map({ (($_ * 2654435761) % 251).chr }).join  => 'near-incompressible',
    ("\c[0]" x 100)                                      => 'a hundred NULs',
    'héllo wörld — ünïcode'                              => 'multi-byte UTF-8',
    ;

say q:to/HEAD/.chomp;
# zlib.vec — conformance vectors for the `zlib` family.
#
# ONE FILE, EVERY IMPLEMENTATION. This distribution's C and (when DATA-PLAN P4
# lands) the engine's own src/DataZlib.cpp are separate implementations on
# purpose — see NATIVE-MODULES-PLAN, "The architecture: independent C". This is
# what keeps them agreeing, so it is read by both and weakened by neither.
#
# Generated by tools/gen-vectors.raku from real libz and the system gzip, never
# from our own code. Compression is not a function, so what is pinned is the
# direction that is: a stream a third party produced must inflate to exactly
# the bytes they compressed.
#
#   I <zlib|gzip|raw> <compressed-hex> <plain-hex>   must inflate to plain
#   X <zlib|gzip|raw> <compressed-hex>               must be REFUSED
#   C <crc32-hex>  <input-hex>
#   A <adler32-hex> <input-hex>
#
# `-` is the empty string in any of those fields.
HEAD

sub emit(Str $kind, *@f) { say ($kind, |@f.map({ $_ || '-' })).join(' ') }

say '';
for @inputs -> $p {
    my $plain = $p.key.encode('utf-8');

    # zlib framing, straight from libz's compress2 at three levels.
    for 1, 6, 9 -> $level {
        emit 'I', 'zlib', hex(compress($plain, $level)), hex($plain);
    }

    # raw deflate and gzip, through libz's own stream with the other
    # window-bits settings — the same settings this module's fallback uses.
    for 'raw' => \(:deflate), 'gzip' => \(:gzip) -> $f {
        my $s = Compress::Zlib::Stream.new(|$f.value);
        my $out = Buf.new($s.deflate(Buf.new($plain)));
        $out ~= Buf.new($_) with $s.finish;
        emit 'I', $f.key, hex($out), hex($plain);
    }

    emit 'C', sprintf('%08x', crc32-of($plain)), hex($plain);
    emit 'A', sprintf('%08x', adler32-of($plain)), hex($plain);
}

# The system gzip, which writes an FNAME field our header parser has to skip —
# a shape libz's own stream never produces.
{
    my $dir = $*TMPDIR.add("czn-gen-{$*PID}");
    $dir.mkdir;
    my $plain = ('gzip writes a name field into its header. ' x 40).encode('utf-8');
    my $f = $dir.add('sample.txt');
    $f.spurt($plain);
    run('gzip', '-9', '-f', $f.Str);
    my $gz = $dir.add('sample.txt.gz').slurp(:bin);
    say '';
    say "# From the system gzip -9, so the FNAME field in the header is exercised.";
    emit 'I', 'gzip', hex($gz), hex($plain);
    .unlink for $dir.dir;
    $dir.rmdir;
}

# Streams that must be REFUSED. Every one is a specific way of being wrong, so
# a decoder that accepts any of them has a real hole rather than a lenience.
say '';
say '# Malformed streams. Each must raise, and none may read out of bounds.';
{
    my $good = compress('hello world hello world'.encode, 6);
    emit 'X', 'zlib', hex(Buf.new(0x00, 0x01, 0x02, 0x03, 0x04, 0x05));   # bad header
    emit 'X', 'zlib', hex($good.subbuf(0, $good.elems - 3));              # truncated
    emit 'X', 'zlib', hex(do { my $b = Buf.new($good); $b[$b.elems - 1] = $b[$b.elems - 1] +^ 0xff; $b });
    emit 'X', 'zlib', hex(do { my $b = Buf.new($good); $b[1] = $b[1] +^ 0x01; $b });  # header check
    emit 'X', 'gzip', hex(Buf.new(0x1f, 0x8b, 0x08, 0x00) ~ Buf.new(0 xx 20));
    emit 'X', 'gzip', hex(Buf.new(0x1f, 0x8c, 0x08, 0x00) ~ Buf.new(0 xx 20));  # bad magic
    emit 'X', 'raw',  hex(Buf.new(0xff, 0xff, 0xff, 0xff));               # invalid block type
    emit 'X', 'raw',  hex(Buf.new(0x01, 0x05, 0x00, 0x00, 0x00));         # stored LEN/NLEN mismatch
}

# CRC-32 and Adler-32 have published check values; they are here so the file
# can be read by an implementation that has no oracle to hand.
say '';
say '# The published check strings.';
emit 'C', 'cbf43926', hex('123456789'.encode);
emit 'A', '091e01de', hex('123456789'.encode);

# --- the oracles for the checksums -----------------------------------------
# libz's crc32/adler32 are not bound by Compress::Zlib::Raw, so these two are
# computed here, in Raku, and checked against the published values above. That
# is enough: an error in either would move the check string.
sub crc32-of(Blob $b) {
    state @t = (^256).map: -> $i {
        my $c = $i;
        $c = $c +& 1 ?? 0xedb88320 +^ ($c +> 1) !! $c +> 1 for ^8;
        $c
    };
    my $c = 0xffffffff;
    $c = @t[($c +^ $_) +& 0xff] +^ ($c +> 8) for $b.list;
    $c +^ 0xffffffff
}
sub adler32-of(Blob $b) {
    my ($s1, $s2) = 1, 0;
    for $b.list { $s1 = ($s1 + $_) % 65521; $s2 = ($s2 + $s1) % 65521 }
    ($s2 +< 16) +| $s1
}
